const assert = require('assert')
const fs = require('fs')

const wxml = fs.readFileSync('miniprogram/pages/auth/login.wxml', 'utf8')
const js = fs.readFileSync('miniprogram/pages/auth/login.js', 'utf8')
const homeWxml = fs.readFileSync('miniprogram/pages/home/home.wxml', 'utf8')
const homeJs = fs.readFileSync('miniprogram/pages/home/home.js', 'utf8')

assert.ok(wxml.includes('患者手机号'))
assert.ok(wxml.includes('医生登录'))
assert.ok(wxml.includes('医生账号'))
assert.ok(wxml.includes('进入医生工作台'))
assert.ok(wxml.includes('type="password"'))
assert.ok(js.includes('loginDoctor'))
assert.ok(js.includes('selectRole'))
assert.ok(js.includes('loginWithWechat'))
assert.ok(!homeWxml.includes('切换身份'))
assert.ok(!homeWxml.includes('bindtap="switchRole"'))
assert.ok(!homeJs.includes('async switchRole'))
